/**
 * What people are interested in, and where each interest sits.
 *
 * Layers: a dozen broad divisions, the fields within them, and beneath those
 * the interests themselves — and it is mostly the interests that are the
 * rooms. Somebody joins `entomology`, not `biology`; the field above it is
 * there to say where entomology *is*, so that it sits near mycology and
 * nowhere near topology before a single person has joined either.
 *
 * It started as fields of study, because academic divisions are the one
 * taxonomy of subjects that people already share. A catalogue of interests is
 * not a university prospectus, though, and most of what anybody wants to talk
 * about is not on one: the match at the weekend, the dog, the rent, the thing
 * they are building in the shed. So it was filled in three passes, and each
 * pass is a different reason for somebody to stay:
 *
 * - **The obvious.** What anybody would look for first — football, cooking,
 *   dogs, television, parenting, personal finance. If these are missing the
 *   place looks empty however much else is here.
 * - **The niche.** Fountain pens, lockpicking, narrowboats, roguelikes. These
 *   are the rooms people cannot find elsewhere, and the ones that keep them.
 * - **The modern.** Large language models, pickleball, heat pumps, the
 *   fediverse. A catalogue without them reads as one nobody has looked at in
 *   ten years.
 *
 * A fourth layer exists where an interest is big enough to have interests of
 * its own: `photography` holds `film photography`, `video games` holds
 * `roguelikes`. Every name here is a room somebody can join, whatever layer it
 * is on; the layers say what is near what, what a join can widen into, and how
 * the catalogue is browsed. Anything it has never heard of still works, it
 * simply goes unanchored.
 *
 * Every entry is `child: parent`, an edge list rather than nested objects:
 * easier to extend by hand, and exactly the shape a tool baking one out of
 * Wikipedia would produce. A name is lowercase letters, digits, spaces and
 * hyphens, thirty-one characters at most, because that is what the server
 * accepts as a subject; `test/catalogue.test.js` holds every entry to it, and
 * catches a name written twice, which an object literal would swallow.
 */
export const knowledge = {
  humanities: 'knowledge',
  arts: 'knowledge',
  'social sciences': 'knowledge',
  'natural sciences': 'knowledge',
  'formal sciences': 'knowledge',
  'applied sciences': 'knowledge',
  hobbies: 'knowledge',
  sport: 'knowledge',
  technology: 'knowledge',
  entertainment: 'knowledge',
  lifestyle: 'knowledge',
  society: 'knowledge',

  // --- humanities ----------------------------------------------------------
  history: 'humanities',
  'ancient history': 'history',
  'medieval history': 'history',
  'modern history': 'history',
  'economic history': 'history',
  'art history': 'history',
  historiography: 'history',
  'military history': 'history',
  'local history': 'history',
  genealogy: 'history',
  'ancient rome': 'history',
  'ancient egypt': 'history',
  'history of science': 'history',
  'oral history': 'history',

  philosophy: 'humanities',
  ethics: 'philosophy',
  logic: 'philosophy',
  metaphysics: 'philosophy',
  epistemology: 'philosophy',
  aesthetics: 'philosophy',
  'philosophy of mind': 'philosophy',
  'political philosophy': 'philosophy',
  phenomenology: 'philosophy',
  stoicism: 'philosophy',
  existentialism: 'philosophy',
  'philosophy of science': 'philosophy',
  'eastern philosophy': 'philosophy',

  literature: 'humanities',
  poetry: 'literature',
  fiction: 'literature',
  drama: 'literature',
  'literary criticism': 'literature',
  'comparative literature': 'literature',
  'book clubs': 'literature',
  audiobooks: 'literature',
  'childrens books': 'literature',
  translation: 'literature',
  'science fiction': 'fiction',
  fantasy: 'fiction',
  'horror fiction': 'fiction',
  'crime fiction': 'fiction',
  'romance novels': 'fiction',
  'historical fiction': 'fiction',
  'literary fiction': 'fiction',
  'young adult fiction': 'fiction',
  'short stories': 'fiction',

  linguistics: 'humanities',
  phonetics: 'linguistics',
  syntax: 'linguistics',
  semantics: 'linguistics',
  'historical linguistics': 'linguistics',
  sociolinguistics: 'linguistics',
  etymology: 'linguistics',
  conlangs: 'linguistics',
  'writing systems': 'linguistics',

  // Learning one, or keeping one up. The commonest reason two strangers have
  // to talk to each other at all.
  languages: 'humanities',
  english: 'languages',
  spanish: 'languages',
  french: 'languages',
  german: 'languages',
  italian: 'languages',
  portuguese: 'languages',
  russian: 'languages',
  arabic: 'languages',
  mandarin: 'languages',
  japanese: 'languages',
  korean: 'languages',
  hindi: 'languages',
  turkish: 'languages',
  dutch: 'languages',
  swedish: 'languages',
  polish: 'languages',
  welsh: 'languages',
  latin: 'languages',
  'sign language': 'languages',
  esperanto: 'languages',
  'language exchange': 'languages',

  archaeology: 'humanities',
  'classical archaeology': 'archaeology',
  'prehistoric archaeology': 'archaeology',
  classics: 'humanities',
  'religious studies': 'humanities',
  theology: 'religious studies',
  'comparative religion': 'religious studies',
  buddhism: 'religious studies',
  christianity: 'religious studies',
  islam: 'religious studies',
  judaism: 'religious studies',
  hinduism: 'religious studies',
  sikhism: 'religious studies',
  mythology: 'religious studies',

  // --- arts ----------------------------------------------------------------
  'visual art': 'arts',
  painting: 'visual art',
  drawing: 'visual art',
  sculpture: 'visual art',
  printmaking: 'visual art',
  ceramics: 'visual art',
  photography: 'visual art',
  illustration: 'visual art',
  watercolour: 'visual art',
  'oil painting': 'visual art',
  'digital art': 'visual art',
  'street art': 'visual art',
  'pixel art': 'visual art',
  'generative art': 'visual art',
  'urban sketching': 'visual art',
  'life drawing': 'visual art',
  collage: 'visual art',
  'film photography': 'photography',
  'street photography': 'photography',
  astrophotography: 'photography',
  'wildlife photography': 'photography',
  'portrait photography': 'photography',
  'landscape photography': 'photography',

  music: 'arts',
  composition: 'music',
  'music theory': 'music',
  musicology: 'music',
  jazz: 'music',
  opera: 'music',
  'electronic music': 'music',
  'folk music': 'music',
  'choral music': 'music',
  rock: 'music',
  pop: 'music',
  'hip hop': 'music',
  metal: 'music',
  punk: 'music',
  'indie music': 'music',
  'classical music': 'music',
  'country music': 'music',
  blues: 'music',
  reggae: 'music',
  soul: 'music',
  funk: 'music',
  rnb: 'music',
  'k-pop': 'music',
  'latin music': 'music',
  afrobeats: 'music',
  'world music': 'music',
  'film scores': 'music',
  'live music': 'music',
  'music festivals': 'music',
  chiptune: 'music',
  techno: 'electronic music',
  'house music': 'electronic music',
  'drum and bass': 'electronic music',
  'ambient music': 'electronic music',
  synthwave: 'electronic music',

  'performing arts': 'arts',
  theatre: 'performing arts',
  dance: 'performing arts',
  puppetry: 'performing arts',
  'musical theatre': 'performing arts',
  improv: 'performing arts',
  'circus arts': 'performing arts',
  'magic tricks': 'performing arts',
  ballet: 'dance',
  'salsa dancing': 'dance',
  'swing dancing': 'dance',
  tango: 'dance',
  'contemporary dance': 'dance',
  'hip hop dance': 'dance',

  film: 'arts',
  cinematography: 'film',
  screenwriting: 'film',
  'film theory': 'film',
  animation: 'film',
  documentaries: 'film',
  'horror films': 'film',
  'world cinema': 'film',
  'classic films': 'film',
  filmmaking: 'film',
  'short films': 'film',

  design: 'arts',
  'graphic design': 'design',
  typography: 'design',
  'industrial design': 'design',
  'textile design': 'design',
  'interior design': 'design',
  'ux design': 'design',
  'web design': 'design',
  'fashion design': 'design',
  'game design': 'design',
  'motion graphics': 'design',

  architecture: 'arts',
  'urban design': 'architecture',
  'landscape architecture': 'architecture',
  'architectural history': 'architecture',
  brutalism: 'architecture',
  'sustainable architecture': 'architecture',

  // --- social sciences -----------------------------------------------------
  anthropology: 'social sciences',
  'cultural anthropology': 'anthropology',
  'biological anthropology': 'anthropology',
  ethnography: 'anthropology',
  folklore: 'anthropology',

  sociology: 'social sciences',
  criminology: 'sociology',
  demography: 'sociology',
  'social theory': 'sociology',
  'gender studies': 'sociology',
  'media studies': 'sociology',

  psychology: 'social sciences',
  'cognitive psychology': 'psychology',
  'developmental psychology': 'psychology',
  'clinical psychology': 'psychology',
  'social psychology': 'psychology',
  psychotherapy: 'psychology',
  'behavioural science': 'psychology',

  economics: 'social sciences',
  microeconomics: 'economics',
  macroeconomics: 'economics',
  econometrics: 'economics',
  'behavioural economics': 'economics',
  'development economics': 'economics',
  'game theory': 'economics',
  'financial markets': 'economics',

  'political science': 'social sciences',
  'international relations': 'political science',
  'public policy': 'political science',
  elections: 'political science',
  'comparative politics': 'political science',

  geography: 'social sciences',
  'human geography': 'geography',
  cartography: 'geography',
  geopolitics: 'geography',
  'urban planning': 'geography',
  'gis mapping': 'geography',

  law: 'social sciences',
  'constitutional law': 'law',
  'criminal law': 'law',
  'international law': 'law',
  'human rights law': 'law',
  'intellectual property': 'law',

  education: 'social sciences',
  pedagogy: 'education',
  teaching: 'education',
  homeschooling: 'education',
  'higher education': 'education',
  'early years education': 'education',
  'online learning': 'education',

  // --- natural sciences ----------------------------------------------------
  physics: 'natural sciences',
  mechanics: 'physics',
  thermodynamics: 'physics',
  optics: 'physics',
  'quantum mechanics': 'physics',
  'particle physics': 'physics',
  astrophysics: 'physics',
  relativity: 'physics',
  'condensed matter': 'physics',
  'nuclear physics': 'physics',
  'fusion energy': 'physics',
  acoustics: 'physics',

  chemistry: 'natural sciences',
  'organic chemistry': 'chemistry',
  'inorganic chemistry': 'chemistry',
  'physical chemistry': 'chemistry',
  biochemistry: 'chemistry',
  'analytical chemistry': 'chemistry',

  biology: 'natural sciences',
  botany: 'biology',
  zoology: 'biology',
  entomology: 'biology',
  mycology: 'biology',
  ornithology: 'biology',
  genetics: 'biology',
  ecology: 'biology',
  microbiology: 'biology',
  'marine biology': 'biology',
  neuroscience: 'biology',
  'evolutionary biology': 'biology',
  herpetology: 'biology',
  primatology: 'biology',
  'molecular biology': 'biology',
  'cell biology': 'biology',
  'synthetic biology': 'biology',
  bioinformatics: 'biology',
  palaeontology: 'biology',

  'earth science': 'natural sciences',
  geology: 'earth science',
  meteorology: 'earth science',
  oceanography: 'earth science',
  hydrology: 'earth science',
  volcanology: 'earth science',
  seismology: 'earth science',
  mineralogy: 'earth science',
  glaciology: 'earth science',

  astronomy: 'natural sciences',
  cosmology: 'astronomy',
  'planetary science': 'astronomy',
  'observational astronomy': 'astronomy',
  exoplanets: 'astronomy',
  astrobiology: 'astronomy',
  'radio astronomy': 'astronomy',

  // --- formal sciences -----------------------------------------------------
  mathematics: 'formal sciences',
  algebra: 'mathematics',
  geometry: 'mathematics',
  topology: 'mathematics',
  'number theory': 'mathematics',
  analysis: 'mathematics',
  combinatorics: 'mathematics',
  probability: 'mathematics',
  calculus: 'mathematics',
  'linear algebra': 'mathematics',
  'graph theory': 'mathematics',
  'category theory': 'mathematics',
  'recreational mathematics': 'mathematics',
  'dynamical systems': 'mathematics',

  statistics: 'formal sciences',
  'bayesian statistics': 'statistics',
  'experimental design': 'statistics',
  'data visualisation': 'statistics',
  'causal inference': 'statistics',

  'computer science': 'formal sciences',
  algorithms: 'computer science',
  compilers: 'computer science',
  databases: 'computer science',
  cryptography: 'computer science',
  'machine learning': 'computer science',
  'computer graphics': 'computer science',
  'distributed systems': 'computer science',
  'programming languages': 'computer science',
  'computer networks': 'computer science',
  'computer architecture': 'computer science',
  'theory of computation': 'computer science',
  'human-computer interaction': 'computer science',
  'computer vision': 'computer science',
  'natural language processing': 'computer science',
  'quantum computing': 'computer science',
  'formal verification': 'computer science',
  'information theory': 'computer science',

  // --- applied sciences ----------------------------------------------------
  engineering: 'applied sciences',
  'civil engineering': 'engineering',
  'mechanical engineering': 'engineering',
  'electrical engineering': 'engineering',
  'chemical engineering': 'engineering',
  'aerospace engineering': 'engineering',
  robotics: 'engineering',
  'materials science': 'engineering',
  'structural engineering': 'engineering',
  'biomedical engineering': 'engineering',
  'renewable energy': 'engineering',
  'nuclear engineering': 'engineering',
  'systems engineering': 'engineering',

  medicine: 'applied sciences',
  anatomy: 'medicine',
  physiology: 'medicine',
  immunology: 'medicine',
  epidemiology: 'medicine',
  psychiatry: 'medicine',
  pharmacology: 'medicine',
  nursing: 'medicine',
  'public health': 'medicine',
  neurology: 'medicine',
  cardiology: 'medicine',
  oncology: 'medicine',
  paediatrics: 'medicine',
  dentistry: 'medicine',
  'veterinary medicine': 'medicine',
  'sports medicine': 'medicine',
  'longevity research': 'medicine',

  agriculture: 'applied sciences',
  agronomy: 'agriculture',
  horticulture: 'agriculture',
  'soil science': 'agriculture',
  permaculture: 'agriculture',
  'regenerative farming': 'agriculture',
  viticulture: 'agriculture',
  livestock: 'agriculture',
  hydroponics: 'agriculture',
  forestry: 'agriculture',

  'environmental science': 'applied sciences',
  conservation: 'environmental science',
  'climate science': 'environmental science',
  rewilding: 'environmental science',
  sustainability: 'environmental science',
  recycling: 'environmental science',
  biodiversity: 'environmental science',

  'information science': 'applied sciences',
  'library science': 'information science',
  'data science': 'information science',
  archives: 'information science',
  'knowledge management': 'information science',
  'open data': 'information science',
  'digital preservation': 'information science',
  'wikipedia editing': 'information science',

  // --- hobbies -------------------------------------------------------------
  // Not fields of study, and the map is poorer without them: most people's
  // interests are not academic, and a catalogue that only admits scholarship
  // has nothing to offer somebody who came for bread and bicycles. Same
  // layers, so a hobby funnels upward exactly as a subfield does.
  handcraft: 'hobbies',
  woodwork: 'handcraft',
  weaving: 'handcraft',
  knitting: 'handcraft',
  quilting: 'handcraft',
  pottery: 'handcraft',
  blacksmithing: 'handcraft',
  bookbinding: 'handcraft',
  glassblowing: 'handcraft',
  leatherwork: 'handcraft',
  'jewellery making': 'handcraft',
  'model making': 'handcraft',
  calligraphy: 'handcraft',
  sewing: 'handcraft',
  embroidery: 'handcraft',
  crochet: 'handcraft',
  'cross-stitch': 'handcraft',
  macrame: 'handcraft',
  origami: 'handcraft',
  'candle making': 'handcraft',
  'soap making': 'handcraft',
  woodturning: 'handcraft',
  whittling: 'handcraft',
  'basket weaving': 'handcraft',
  'miniature painting': 'handcraft',
  'furniture restoration': 'handcraft',
  'hand spinning': 'handcraft',
  'natural dyeing': 'handcraft',
  'knife making': 'handcraft',

  cooking: 'hobbies',
  baking: 'cooking',
  'bread making': 'cooking',
  pastry: 'cooking',
  fermentation: 'cooking',
  brewing: 'cooking',
  barbecue: 'cooking',
  preserving: 'cooking',
  cheesemaking: 'cooking',
  sourdough: 'bread making',
  kombucha: 'fermentation',
  'vegan cooking': 'cooking',
  'vegetarian cooking': 'cooking',
  'meal prep': 'cooking',
  'italian cooking': 'cooking',
  'indian cooking': 'cooking',
  'chinese cooking': 'cooking',
  'japanese cooking': 'cooking',
  'mexican cooking': 'cooking',
  'thai cooking': 'cooking',
  'french cooking': 'cooking',
  'korean cooking': 'cooking',
  'middle eastern cooking': 'cooking',
  'street food': 'cooking',
  'pizza making': 'cooking',
  'pasta making': 'cooking',
  'hot sauce': 'cooking',
  'cast iron cooking': 'cooking',
  'chocolate making': 'cooking',

  // What is in the glass. Coffee and tea used to sit under cooking, where
  // nobody would look for them.
  drinks: 'hobbies',
  coffee: 'drinks',
  tea: 'drinks',
  espresso: 'coffee',
  'home roasting': 'coffee',
  'pour over coffee': 'coffee',
  wine: 'drinks',
  'natural wine': 'wine',
  'craft beer': 'drinks',
  whisky: 'drinks',
  cocktails: 'drinks',
  'mead making': 'drinks',
  'cider making': 'drinks',
  'alcohol-free drinks': 'drinks',

  games: 'hobbies',
  chess: 'games',
  go: 'games',
  'board games': 'games',
  'tabletop roleplaying': 'games',
  'video games': 'games',
  puzzles: 'games',
  'card games': 'games',
  'dungeons and dragons': 'tabletop roleplaying',
  'miniature wargaming': 'games',
  'magic the gathering': 'card games',
  poker: 'card games',
  bridge: 'card games',
  mahjong: 'games',
  backgammon: 'games',
  crosswords: 'puzzles',
  sudoku: 'puzzles',
  'jigsaw puzzles': 'puzzles',
  speedcubing: 'puzzles',
  'escape rooms': 'games',
  'pub quizzes': 'games',
  pinball: 'games',
  'arcade games': 'games',
  roguelikes: 'video games',
  'strategy games': 'video games',
  'role-playing games': 'video games',
  'first-person shooters': 'video games',
  'fighting games': 'video games',
  'simulation games': 'video games',
  'indie games': 'video games',
  'cozy games': 'video games',
  'retro gaming': 'video games',
  speedrunning: 'video games',
  esports: 'video games',
  mmos: 'video games',
  minecraft: 'video games',
  pokemon: 'video games',
  nintendo: 'video games',
  'pc gaming': 'video games',
  'console gaming': 'video games',
  'mobile gaming': 'video games',
  'game modding': 'video games',
  'interactive fiction': 'video games',

  outdoors: 'hobbies',
  hiking: 'outdoors',
  climbing: 'outdoors',
  cycling: 'outdoors',
  sailing: 'outdoors',
  running: 'outdoors',
  kayaking: 'outdoors',
  camping: 'outdoors',
  foraging: 'outdoors',
  fishing: 'outdoors',
  birdwatching: 'outdoors',
  stargazing: 'outdoors',
  'trail running': 'running',
  'marathon running': 'running',
  ultrarunning: 'running',
  parkrun: 'running',
  'road cycling': 'cycling',
  'mountain biking': 'cycling',
  'gravel cycling': 'cycling',
  bikepacking: 'cycling',
  'e-bikes': 'cycling',
  'pro cycling': 'cycling',
  bmx: 'cycling',
  bouldering: 'climbing',
  mountaineering: 'climbing',
  'wild camping': 'camping',
  'fly fishing': 'fishing',
  'sea fishing': 'fishing',
  'ultralight backpacking': 'outdoors',
  'wild swimming': 'outdoors',
  paddleboarding: 'outdoors',
  canoeing: 'outdoors',
  geocaching: 'outdoors',
  orienteering: 'outdoors',
  'metal detecting': 'outdoors',
  'horse riding': 'outdoors',
  'national parks': 'outdoors',
  bushcraft: 'outdoors',
  overlanding: 'outdoors',
  caving: 'outdoors',
  beachcombing: 'outdoors',

  growing: 'hobbies',
  gardening: 'growing',
  houseplants: 'growing',
  bonsai: 'growing',
  beekeeping: 'growing',
  'vegetable growing': 'growing',
  'native plants': 'growing',
  orchids: 'growing',
  'cacti and succulents': 'growing',
  'carnivorous plants': 'growing',
  composting: 'growing',
  allotments: 'growing',
  'herb growing': 'growing',
  'fruit trees': 'growing',
  'greenhouse growing': 'growing',
  'mushroom growing': 'growing',
  terrariums: 'growing',
  'lawn care': 'growing',
  'seed saving': 'growing',
  'balcony gardening': 'growing',
  'backyard chickens': 'growing',

  movement: 'hobbies',
  yoga: 'movement',
  'martial arts': 'movement',
  swimming: 'movement',
  weightlifting: 'movement',
  skateboarding: 'movement',
  surfing: 'movement',
  karate: 'martial arts',
  taekwondo: 'martial arts',
  'kung fu': 'martial arts',
  aikido: 'martial arts',
  capoeira: 'martial arts',
  pilates: 'movement',
  'tai chi': 'movement',
  parkour: 'movement',
  calisthenics: 'movement',
  crossfit: 'movement',
  powerlifting: 'movement',
  bodybuilding: 'movement',
  kettlebells: 'movement',
  'home workouts': 'movement',
  rollerskating: 'movement',

  tinkering: 'hobbies',
  electronics: 'tinkering',
  '3d printing': 'tinkering',
  'amateur radio': 'tinkering',
  drones: 'tinkering',
  'retro computing': 'tinkering',
  'car restoration': 'tinkering',
  'model trains': 'tinkering',
  arduino: 'tinkering',
  'raspberry pi': 'tinkering',
  lockpicking: 'tinkering',
  watchmaking: 'tinkering',
  'bicycle mechanics': 'tinkering',
  'motorcycle maintenance': 'tinkering',
  'model rocketry': 'tinkering',
  'radio control models': 'tinkering',
  lego: 'tinkering',
  'cnc machining': 'tinkering',
  'laser cutting': 'tinkering',
  'pcb design': 'tinkering',
  'off-grid power': 'tinkering',
  'knife sharpening': 'tinkering',

  collections: 'hobbies',
  'stamp collecting': 'collections',
  'coin collecting': 'collections',
  'record collecting': 'collections',
  'book collecting': 'collections',
  antiques: 'collections',
  'comic collecting': 'collections',
  'trading cards': 'collections',
  'fountain pens': 'collections',
  'vintage cameras': 'collections',
  'mineral collecting': 'collections',
  'fossil hunting': 'collections',
  'toy collecting': 'collections',
  'art collecting': 'collections',
  'map collecting': 'collections',
  typewriters: 'collections',
  postcards: 'collections',

  'playing music': 'hobbies',
  guitar: 'playing music',
  piano: 'playing music',
  singing: 'playing music',
  drumming: 'playing music',
  djing: 'playing music',
  songwriting: 'playing music',
  'bass guitar': 'playing music',
  violin: 'playing music',
  cello: 'playing music',
  ukulele: 'playing music',
  saxophone: 'playing music',
  synthesizers: 'playing music',
  'modular synths': 'synthesizers',
  'music production': 'playing music',
  'home recording': 'playing music',
  beatmaking: 'playing music',
  choirs: 'playing music',
  busking: 'playing music',
  'playing in bands': 'playing music',
  'open mic nights': 'playing music',

  writing: 'hobbies',
  'creative writing': 'writing',
  journaling: 'writing',
  zines: 'writing',
  'novel writing': 'writing',
  blogging: 'writing',
  newsletters: 'writing',
  'fan fiction': 'writing',
  worldbuilding: 'writing',
  copywriting: 'writing',
  'technical writing': 'writing',
  'pen pals': 'writing',

  // --- sport ---------------------------------------------------------------
  // Playing it and following it, which for most sports are the same room.
  'team sports': 'sport',
  football: 'team sports',
  'american football': 'team sports',
  basketball: 'team sports',
  baseball: 'team sports',
  cricket: 'team sports',
  'rugby union': 'team sports',
  'rugby league': 'team sports',
  'ice hockey': 'team sports',
  volleyball: 'team sports',
  handball: 'team sports',
  'field hockey': 'team sports',
  lacrosse: 'team sports',
  netball: 'team sports',
  softball: 'team sports',
  'ultimate frisbee': 'team sports',
  'australian rules football': 'team sports',
  'gaelic games': 'team sports',
  'water polo': 'team sports',
  futsal: 'team sports',
  'womens football': 'football',
  'fantasy football': 'football',
  'five-a-side': 'football',
  'football tactics': 'football',
  'non-league football': 'football',

  'racket sports': 'sport',
  tennis: 'racket sports',
  badminton: 'racket sports',
  'table tennis': 'racket sports',
  squash: 'racket sports',
  pickleball: 'racket sports',
  padel: 'racket sports',

  motorsport: 'sport',
  'formula 1': 'motorsport',
  'formula e': 'motorsport',
  rallying: 'motorsport',
  motogp: 'motorsport',
  nascar: 'motorsport',
  indycar: 'motorsport',
  'endurance racing': 'motorsport',
  karting: 'motorsport',
  'sim racing': 'motorsport',

  'combat sports': 'sport',
  boxing: 'combat sports',
  'mixed martial arts': 'combat sports',
  wrestling: 'combat sports',
  judo: 'combat sports',
  'brazilian jiu-jitsu': 'combat sports',
  fencing: 'combat sports',
  kickboxing: 'combat sports',
  'muay thai': 'combat sports',
  sumo: 'combat sports',
  'pro wrestling': 'combat sports',

  athletics: 'sport',
  'track and field': 'athletics',
  gymnastics: 'athletics',
  triathlon: 'athletics',
  rowing: 'athletics',
  'obstacle racing': 'athletics',
  cyclocross: 'athletics',

  'target sports': 'sport',
  golf: 'target sports',
  'disc golf': 'target sports',
  snooker: 'target sports',
  pool: 'target sports',
  darts: 'target sports',
  'tenpin bowling': 'target sports',
  'lawn bowls': 'target sports',
  archery: 'target sports',
  croquet: 'target sports',
  petanque: 'target sports',

  'winter sports': 'sport',
  skiing: 'winter sports',
  snowboarding: 'winter sports',
  'cross-country skiing': 'winter sports',
  'ski touring': 'winter sports',
  'figure skating': 'winter sports',
  'speed skating': 'winter sports',
  curling: 'winter sports',
  biathlon: 'winter sports',

  'water sports': 'sport',
  windsurfing: 'water sports',
  kitesurfing: 'water sports',
  wakeboarding: 'water sports',
  diving: 'water sports',
  'scuba diving': 'water sports',
  freediving: 'water sports',
  'dragon boating': 'water sports',

  'following sport': 'sport',
  olympics: 'following sport',
  paralympics: 'following sport',
  'fantasy sports': 'following sport',
  'sports analytics': 'following sport',
  'sports history': 'following sport',
  coaching: 'following sport',
  'grassroots sport': 'following sport',
  'womens sport': 'following sport',

  // --- technology ----------------------------------------------------------
  // Using it and making it, as opposed to the study of it, which is computer
  // science and sits with the formal sciences.
  programming: 'technology',
  python: 'programming',
  javascript: 'programming',
  typescript: 'programming',
  rust: 'programming',
  golang: 'programming',
  java: 'programming',
  'c programming': 'programming',
  cpp: 'programming',
  'c sharp': 'programming',
  kotlin: 'programming',
  swift: 'programming',
  php: 'programming',
  ruby: 'programming',
  elixir: 'programming',
  haskell: 'programming',
  lisp: 'programming',
  zig: 'programming',
  sql: 'programming',
  'functional programming': 'programming',
  'web development': 'programming',
  'frontend development': 'web development',
  'backend development': 'web development',
  webassembly: 'web development',
  'mobile development': 'programming',
  'game development': 'programming',
  'embedded programming': 'programming',
  devops: 'programming',
  'data engineering': 'programming',
  'open source': 'programming',
  'software architecture': 'programming',
  'competitive programming': 'programming',
  'learning to code': 'programming',
  'creative coding': 'programming',
  'code golf': 'programming',
  'text editors': 'programming',
  spreadsheets: 'programming',

  'artificial intelligence': 'technology',
  'large language models': 'artificial intelligence',
  'ai agents': 'artificial intelligence',
  'ai coding tools': 'artificial intelligence',
  'ai art': 'artificial intelligence',
  'ai music': 'artificial intelligence',
  'ai safety': 'artificial intelligence',
  'ai ethics': 'artificial intelligence',
  'open source ai': 'artificial intelligence',
  'prompt writing': 'artificial intelligence',

  gadgets: 'technology',
  smartphones: 'gadgets',
  'pc building': 'gadgets',
  'mechanical keyboards': 'gadgets',
  wearables: 'gadgets',
  'home automation': 'gadgets',
  'e-readers': 'gadgets',
  'hi-fi': 'gadgets',
  headphones: 'gadgets',
  'home cinema': 'gadgets',
  'virtual reality': 'gadgets',
  'augmented reality': 'gadgets',

  internet: 'technology',
  fediverse: 'internet',
  'indie web': 'internet',
  'online privacy': 'internet',
  'self-hosting': 'internet',
  homelab: 'internet',
  'mesh networking': 'internet',
  memes: 'internet',
  wikis: 'internet',
  'online communities': 'internet',

  cybersecurity: 'technology',
  'ethical hacking': 'cybersecurity',
  'capture the flag': 'cybersecurity',
  osint: 'cybersecurity',
  'bug bounties': 'cybersecurity',
  'digital forensics': 'cybersecurity',
  'malware analysis': 'cybersecurity',
  'network security': 'cybersecurity',

  'operating systems': 'technology',
  linux: 'operating systems',
  macos: 'operating systems',
  windows: 'operating systems',
  android: 'operating systems',
  ios: 'operating systems',
  bsd: 'operating systems',
  'command line': 'operating systems',

  'emerging technology': 'technology',
  spaceflight: 'emerging technology',
  satellites: 'emerging technology',
  'self-driving cars': 'emerging technology',
  cryptocurrency: 'emerging technology',
  blockchain: 'emerging technology',
  biotechnology: 'emerging technology',
  'gene editing': 'emerging technology',
  'brain-computer interfaces': 'emerging technology',
  'humanoid robots': 'emerging technology',
  'battery technology': 'emerging technology',
  'solar power': 'emerging technology',
  'heat pumps': 'emerging technology',
  nanotechnology: 'emerging technology',
  'carbon capture': 'emerging technology',

  'tech industry': 'technology',
  startups: 'tech industry',
  'indie hacking': 'tech industry',
  'product management': 'tech industry',
  'tech careers': 'tech industry',
  'no-code tools': 'tech industry',
  'tech policy': 'tech industry',
  'tech news': 'tech industry',

  // --- entertainment -------------------------------------------------------
  // What people watch and listen to and are fans of. Film and music are with
  // the arts and games are with the hobbies, where they already were.
  television: 'entertainment',
  'tv drama': 'television',
  sitcoms: 'television',
  'reality tv': 'television',
  'k-drama': 'television',
  'soap operas': 'television',
  'game shows': 'television',
  'crime drama': 'television',
  'science fiction tv': 'television',
  'animated series': 'television',
  'classic tv': 'television',

  'anime and manga': 'entertainment',
  anime: 'anime and manga',
  manga: 'anime and manga',
  'studio ghibli': 'anime and manga',
  'light novels': 'anime and manga',
  webtoons: 'anime and manga',
  vtubers: 'anime and manga',

  comics: 'entertainment',
  'superhero comics': 'comics',
  'graphic novels': 'comics',
  webcomics: 'comics',
  'indie comics': 'comics',
  'comic strips': 'comics',
  'bandes dessinees': 'comics',

  'podcasts and radio': 'entertainment',
  podcasts: 'podcasts and radio',
  'true crime': 'podcasts and radio',
  'comedy podcasts': 'podcasts and radio',
  'history podcasts': 'podcasts and radio',
  'audio drama': 'podcasts and radio',
  radio: 'podcasts and radio',
  podcasting: 'podcasts and radio',

  'pop culture': 'entertainment',
  'star wars': 'pop culture',
  'star trek': 'pop culture',
  'doctor who': 'pop culture',
  tolkien: 'pop culture',
  'harry potter': 'pop culture',
  marvel: 'pop culture',
  disney: 'pop culture',
  'theme parks': 'pop culture',
  cosplay: 'pop culture',
  conventions: 'pop culture',
  'fan art': 'pop culture',
  'celebrity news': 'pop culture',
  'award shows': 'pop culture',
  eurovision: 'pop culture',
  nostalgia: 'pop culture',

  'online video': 'entertainment',
  youtube: 'online video',
  'live streaming': 'online video',
  'short-form video': 'online video',
  'video essays': 'online video',
  asmr: 'online video',
  'content creation': 'online video',
  vlogging: 'online video',

  comedy: 'entertainment',
  'stand-up comedy': 'comedy',
  'sketch comedy': 'comedy',
  satire: 'comedy',
  'comedy writing': 'comedy',
  'panel shows': 'comedy',

  // --- lifestyle -----------------------------------------------------------
  // The rest of life: where you live, who with, what it costs, how you feel.
  home: 'lifestyle',
  'home improvement': 'home',
  renovation: 'home',
  'home decorating': 'home',
  decluttering: 'home',
  minimalism: 'home',
  'tiny houses': 'home',
  homesteading: 'home',
  'off-grid living': 'home',
  'buying a home': 'home',
  renting: 'home',
  'zero waste': 'home',

  'family and relationships': 'lifestyle',
  parenting: 'family and relationships',
  'new parents': 'parenting',
  'parenting teens': 'parenting',
  'single parents': 'parenting',
  pregnancy: 'family and relationships',
  'adoption and fostering': 'family and relationships',
  dating: 'family and relationships',
  relationships: 'family and relationships',
  weddings: 'family and relationships',
  friendship: 'family and relationships',
  carers: 'family and relationships',
  bereavement: 'family and relationships',

  money: 'lifestyle',
  'personal finance': 'money',
  investing: 'money',
  'index funds': 'investing',
  'property investing': 'investing',
  budgeting: 'money',
  'frugal living': 'money',
  'financial independence': 'money',
  'retirement planning': 'money',
  'side hustles': 'money',
  'getting out of debt': 'money',

  work: 'lifestyle',
  careers: 'work',
  'job hunting': 'work',
  'career change': 'work',
  'remote work': 'work',
  freelancing: 'work',
  'small business': 'work',
  entrepreneurship: 'work',
  management: 'work',
  productivity: 'work',
  'public speaking': 'work',
  'skilled trades': 'work',
  'four-day week': 'work',
  'work-life balance': 'work',

  wellbeing: 'lifestyle',
  'mental health': 'wellbeing',
  anxiety: 'mental health',
  'self-care': 'mental health',
  meditation: 'wellbeing',
  mindfulness: 'wellbeing',
  breathwork: 'wellbeing',
  sleep: 'wellbeing',
  nutrition: 'wellbeing',
  'healthy eating': 'wellbeing',
  'intermittent fasting': 'wellbeing',
  sobriety: 'wellbeing',
  'chronic illness': 'wellbeing',
  adhd: 'wellbeing',
  autism: 'wellbeing',
  'digital minimalism': 'wellbeing',
  'cold water therapy': 'wellbeing',
  sauna: 'wellbeing',
  'quantified self': 'wellbeing',
  'womens health': 'wellbeing',
  'mens health': 'wellbeing',
  menopause: 'wellbeing',
  'ageing well': 'wellbeing',

  travel: 'lifestyle',
  backpacking: 'travel',
  'city breaks': 'travel',
  'road trips': 'travel',
  'solo travel': 'travel',
  'budget travel': 'travel',
  'family travel': 'travel',
  'train travel': 'travel',
  cruises: 'travel',
  'van life': 'travel',
  'digital nomads': 'travel',
  'travel hacking': 'travel',
  'slow travel': 'travel',
  'expat life': 'travel',
  'travel in europe': 'travel',
  'travel in asia': 'travel',
  'travel in africa': 'travel',
  'travel in the americas': 'travel',
  'travel in oceania': 'travel',

  pets: 'lifestyle',
  dogs: 'pets',
  'dog training': 'dogs',
  puppies: 'dogs',
  'dog sports': 'dogs',
  cats: 'pets',
  'rescue animals': 'pets',
  aquariums: 'pets',
  aquascaping: 'aquariums',
  reptiles: 'pets',
  'pet birds': 'pets',
  rabbits: 'pets',
  'small pets': 'pets',
  horses: 'pets',
  'invertebrate pets': 'pets',

  style: 'lifestyle',
  fashion: 'style',
  streetwear: 'style',
  sneakers: 'style',
  'vintage clothing': 'style',
  thrifting: 'style',
  'sustainable fashion': 'style',
  menswear: 'style',
  'capsule wardrobes': 'style',
  'raw denim': 'style',
  'alternative fashion': 'style',
  watches: 'style',
  jewellery: 'style',
  skincare: 'style',
  makeup: 'style',
  hair: 'style',
  fragrance: 'style',
  'nail art': 'style',
  tattoos: 'style',

  vehicles: 'lifestyle',
  cars: 'vehicles',
  'classic cars': 'cars',
  'electric vehicles': 'cars',
  'car detailing': 'cars',
  'learning to drive': 'cars',
  motorcycles: 'vehicles',
  'campervan conversions': 'vehicles',
  aviation: 'vehicles',
  'plane spotting': 'aviation',
  'flight simulation': 'aviation',
  'private pilots': 'aviation',
  railways: 'vehicles',
  trainspotting: 'railways',
  'heritage railways': 'railways',
  boating: 'vehicles',
  narrowboats: 'boating',
  buses: 'vehicles',
  'public transport': 'vehicles',

  // --- society -------------------------------------------------------------
  // What is going on, what people want done about it, and who they are to
  // each other.
  'current affairs': 'society',
  'world news': 'current affairs',
  politics: 'current affairs',
  'local news': 'current affairs',
  'business news': 'current affairs',
  'science news': 'current affairs',
  journalism: 'current affairs',
  'fact checking': 'current affairs',
  'media literacy': 'current affairs',
  'good news': 'current affairs',
  'long reads': 'current affairs',

  causes: 'society',
  'climate action': 'causes',
  volunteering: 'causes',
  'animal welfare': 'causes',
  'human rights': 'causes',
  housing: 'causes',
  urbanism: 'causes',
  'active travel': 'causes',
  'community organising': 'causes',
  'mutual aid': 'causes',
  'charity fundraising': 'causes',
  'trade unions': 'causes',
  'refugee support': 'causes',
  'disability rights': 'causes',
  'right to repair': 'causes',
  'digital rights': 'causes',
  'effective altruism': 'causes',
  veganism: 'causes',

  communities: 'society',
  lgbtq: 'communities',
  students: 'communities',
  'mature students': 'students',
  'international students': 'students',
  'new in town': 'communities',
  neighbours: 'communities',
  veterans: 'communities',
  'over 50s': 'communities',
  'deaf community': 'communities',
  'rural life': 'communities',
  'city life': 'communities',
  meetups: 'communities',
  coworking: 'communities',
  'night owls': 'communities',
  'early birds': 'communities',
};

/**
 * What people type when they mean one of the above.
 *
 * Search is by the letters in a name, and the name somebody has in their head
 * is often not the catalogue's: `soccer` finds nothing in a list that says
 * `football`, and the next thing they do is make an empty room called
 * `soccer` beside the full one. Each of these points at the name they were
 * after, so the search can offer it.
 *
 * Only for search. Nothing here renames a room somebody deliberately makes:
 * `fire` means financial independence to the people who use it that way, and
 * something else entirely to a firefighter.
 */
export const alsoCalled = {
  // sport
  soccer: 'football',
  nfl: 'american football',
  nba: 'basketball',
  f1: 'formula 1',
  mma: 'mixed martial arts',
  ufc: 'mixed martial arts',
  bjj: 'brazilian jiu-jitsu',
  'ping pong': 'table tennis',
  bowling: 'tenpin bowling',
  gym: 'weightlifting',
  lifting: 'weightlifting',
  jogging: 'running',
  biking: 'cycling',
  bikes: 'cycling',
  mtb: 'mountain biking',
  trekking: 'hiking',
  birding: 'birdwatching',
  sup: 'paddleboarding',

  // games and entertainment
  gaming: 'video games',
  dnd: 'dungeons and dragons',
  ttrpg: 'tabletop roleplaying',
  rpg: 'role-playing games',
  mtg: 'magic the gathering',
  fps: 'first-person shooters',
  warhammer: 'miniature wargaming',
  quiz: 'pub quizzes',
  trivia: 'pub quizzes',
  movies: 'film',
  cinema: 'film',
  tv: 'television',
  telly: 'television',
  kdrama: 'k-drama',
  kpop: 'k-pop',
  'sci-fi': 'science fiction',
  scifi: 'science fiction',
  ya: 'young adult fiction',
  books: 'book clubs',
  reading: 'book clubs',
  twitch: 'live streaming',
  streaming: 'live streaming',
  tiktok: 'short-form video',
  standup: 'stand-up comedy',

  // music
  rap: 'hip hop',
  edm: 'electronic music',
  dnb: 'drum and bass',
  'r&b': 'rnb',
  synths: 'synthesizers',
  vinyl: 'record collecting',
  gigs: 'live music',
  concerts: 'live music',

  // technology
  ai: 'artificial intelligence',
  llm: 'large language models',
  llms: 'large language models',
  chatbots: 'large language models',
  ml: 'machine learning',
  coding: 'programming',
  js: 'javascript',
  ts: 'typescript',
  'c++': 'cpp',
  'c#': 'c sharp',
  infosec: 'cybersecurity',
  hacking: 'ethical hacking',
  ctf: 'capture the flag',
  crypto: 'cryptocurrency',
  bitcoin: 'cryptocurrency',
  ev: 'electric vehicles',
  evs: 'electric vehicles',
  vr: 'virtual reality',
  ar: 'augmented reality',
  'smart home': 'home automation',
  selfhosted: 'self-hosting',
  mastodon: 'fediverse',
  space: 'spaceflight',
  keyboards: 'mechanical keyboards',

  // study
  math: 'mathematics',
  maths: 'mathematics',
  stats: 'statistics',
  cs: 'computer science',
  psych: 'psychology',
  econ: 'economics',
  dinosaurs: 'palaeontology',
  paleontology: 'palaeontology',
  chinese: 'mandarin',
  asl: 'sign language',
  bsl: 'sign language',

  // food and drink
  bread: 'bread making',
  bbq: 'barbecue',
  beer: 'craft beer',
  whiskey: 'whisky',

  // the rest of life
  diy: 'home improvement',
  fire: 'financial independence',
  stocks: 'investing',
  wfh: 'remote work',
  jobs: 'job hunting',
  therapy: 'psychotherapy',
  sober: 'sobriety',
  diet: 'healthy eating',
  kids: 'parenting',
  mums: 'parenting',
  moms: 'parenting',
  dads: 'parenting',
  'fish tanks': 'aquariums',
  fishkeeping: 'aquariums',
  trains: 'railways',
  planes: 'aviation',
  motorbikes: 'motorcycles',
  perfume: 'fragrance',
  trainers: 'sneakers',
  news: 'world news',
  lgbt: 'lgbtq',
  queer: 'lgbtq',
  uni: 'students',
  university: 'students',
  college: 'students',
};

/** The fields — the layer above what people join. */
export const fields = Object.keys(knowledge).filter(
  (name) => knowledge[Object.keys(knowledge).find((k) => k === name)] !== undefined,
);

/** Subjects with nothing beneath them: the narrowest rooms there are. */
export function subfields(parents = knowledge) {
  const hasChildren = new Set(Object.values(parents));
  return Object.keys(parents).filter((name) => !hasChildren.has(name)).sort();
}

/**
 * What sits directly under each name, sorted, with the divisions under
 * `knowledge`. Built once: the catalogue is browsed a level at a time, and
 * walking eleven hundred entries for every level would be the whole cost of
 * doing so.
 */
export function childrenOf(parents = knowledge) {
  const under = new Map();
  for (const [child, parent] of Object.entries(parents)) {
    if (!under.has(parent)) under.set(parent, []);
    under.get(parent).push(child);
  }
  for (const kids of under.values()) kids.sort();
  return under;
}
